version: '2'
services:
    cafesitot-app:
        image: cafesitot
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cafesitot-postgresql:5432/CafeSiTot
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cafesitot-postgresql:
        extends:
            file: postgresql.yml
            service: cafesitot-postgresql
